### ISSUE TITLE
Project 04 지하철역 주변 아파트 가격 알아보기에서

### ISSUE THREAD

**Issue by newstars** [newstars/HelloR#11]
Project 04 지하철역 주변 아파트 가격 알아보기에서

install_github("dkahle/ggmap")

를 실행하면 아래와 같은 오류가 발생합니다.

ERROR: dependencies 'glue', 'rlang' are not available for package 'ggmap'
 removing 'C:/Users/HJKIM-PC/Documents/R/win-library/3.3/ggmap'
Error: Command failed (1)

어떻게 수정해야 하나요?

_Originally posted by @merrybingo in https://github.com/newstars/HelloR/issues/1#issuecomment-484206310_

**Comment by newstars** [comment]
안녕하세요. 
에러로그에서 처럼  기존에 ggmap이 설치되어 발생하는 문제 입니다.
removing 'C:/Users/HJKIM-PC/Documents/R/win-library/3.3/ggmap'

해당 패키지를 먼저 삭제하시고, 재설치하시면 됩니다.

**Comment by merrybingo** [comment]
1. remove.packages("ggmap") 으로 제거하려하면 
Error in remove.packages : there is no package called ‘ggmap’, 처럼 설치되지 않았다고 뜨고

2. C:\Users\HJKIM-PC\Documents\R\win-library\3.3 폴더에서 직접 삭제하려 해도 
ggmap 폴더가 존재하지 않습니다.

**Comment by newstars** [comment]
현재 devtools 가 3.5.2 버전이네요. 보내주신 경로상으로는 3.3 버전이라 우선 버전 업그레이드를 해보시길 바랍니다.

> library(devtools)
Warning message:
package ‘devtools’ was built under R version 3.5.2 

이후에도 동일하면 의존성 패키지인 glue, rlang 를 따로 설치하시고, 다시 시도해보세요.

**Comment by merrybingo** [comment]
버전 업그레이드로 해결했습니다 
감사합니다.

**Comment by newstars** [comment]
다행이네요~ 즐거운 실습 되시길 바랍니다.
