### ISSUE TITLE
질문입니다.

### ISSUE THREAD

**Issue by echobox2** [newstars/HelloR#12]
안녕하세요 
책을 통해 도움을 많이 받고 있습니다. 감사합니다.
그런데,
ggmap을 실행하면 다음과 같은 에러가 나오네요
 gc <- geocode(enc2utf8('서울'))
Source : https://maps.googleapis.com/maps/api/geocode/json?address=%EC%84%9C%EC%9A%B8&key=xxx-uZynXXXXXXXXXB5NxUHjywg
Warning: Geocoding "서울" failed with error:
This API project is not authorized to use this API.

어떻게 해야할까요
답변 미리 감사합니다.

**Comment by newstars** [comment]
안녕하세요.

This API project is not authorized to use this API.

해당 에러는 사용하시는 구글 키 이슈인듯 합니다.

구글 프로젝트 확인해보시면 될듯 합니다.
https://console.cloud.google.com

구글 프로젝트는 다음 영상에서 보실수 있습니다.
https://www.youtube.com/watch?v=yZpBDOjlko0

감사합니다.

**Comment by jooseokkim** [comment]
한글  분석을 위해 KoNLP를 Install하고,
 library(KoNLP) 눌렀을때, 다음 의 Error message 나타납니다.
해결하기 위해 다음의 절차를 진행해 보았는데, Error가 해결이 안됩니다.

1. Error 메시지
Error: package or namespace load failed for ‘KoNLP’:
 .onLoad가 loadNamespace()에서 'rJava'때문에 실패했습니다:
  호출: inDL(x, as.logical(local), as.logical(now), ...)
  에러: unable to load shared object 'C:/Users/USER/Documents/R/win-library/3.6/rJava/libs/x64/rJava.dll':
  LoadLibrary failure:  지정된 모듈을 찾을 수 없습니다.

(해결 노력)
### 1. Java PGM 다운로드 들어가서, Version 8 Updating 211 버젼 다운로드 설치 완료함.
PGM명 :   JavaSetup8u211

### 2. RStudio로 돌아가서,
> install.packages("rJava") 실시
---> package ‘rJava’ successfully unpacked and MD5 sums checked가 나타나는데, 다음의 Warning이
       나타남.

WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/USER/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/rJava_0.9-11.zip'
Content type 'application/zip' length 831952 bytes (812 KB)
downloaded 812 KB

package ‘rJava’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\USER\AppData\Local\Temp\RtmpUbsi9F\downloaded_packages

### 3.library(rJava) 누르면, 다음의 메시지 나타남.

> library(rJava)
Error: package or namespace load failed for ‘rJava’:
 .onLoad가 loadNamespace()에서 'rJava'때문에 실패했습니다:
  호출: inDL(x, as.logical(local), as.logical(now), ...)
  에러: unable to load shared object 'C:/Users/USER/Documents/R/win-library/3.6/rJava/libs/x64/rJava.dll':
  LoadLibrary failure:  지정된 모듈을 찾을 수 없습니다.

---> Java를 설치했는데, 왜 Error가 나타나는지요 ?

### 4. library(KoNLP) 를 눌러도, 다음의 동일한 메시지 나타남.


> library(KoNLP)
Error: package or namespace load failed for ‘KoNLP’:
 .onLoad가 loadNamespace()에서 'rJava'때문에 실패했습니다:
  호출: inDL(x, as.logical(local), as.logical(now), ...)
  에러: unable to load shared object 'C:/Users/USER/Documents/R/win-library/3.6/rJava/libs/x64/rJava.dll':
  LoadLibrary failure:  지정된 모듈을 찾을 수 없습니다.


-----> 인터넷의 Error 해결 가이드대로 해도 안됩니다.
          도움 부탁드립니다.

**Comment by jooseokkim** [comment]
혹시 원격지원을 받을 방법이 없을까요 ?

**Comment by SeongDahun** [comment]
> echobox2

혹시 해결하셨을까요?
