### ISSUE TITLE
p81. mac OX Studio 원시자료입력에 대해서 문의드립니다.

### ISSUE THREAD

**Issue by jackrod12** [newstars/HelloR#13]
저자님 안녕하세요.
'처음 시작하는 R데이터 분석'으로 R 독학 중인 독자입니다.

81페이지의 '원시자료입력 및 엑셀파일 가져오기' 파트에서
'readxl 패키지 설치' 와 '데이터 세트로 저장' 에 대한 문의를 드립니다.

mac OX를 사용하고 있기 때문에 C드라이브가 아닌, 유저 폴더(Jackrod)에 Rstudy 폴더를 개설했는데요.

install.packages("readxl")
library(readxl)

로 readxl 패키지 설치 및 로드를 했을 때 "Installing package into ~" 라는 내용이 보이지 않습니다.
따라서 테이터 불러오기를 하더라도, 해당 데이터를 찾을 수 없다고 확인되구요.

윈도우버전과 max OX를 사용했을 때 혹시 다르게 따져봐야하는 지점이 있는지 문의드립니다.

**Comment by newstars** [comment]
안녕하세요.

저 역시도 주로 맥을 쓰고 있습니다.

맥이라고 해서 별달리 설정하는 것이 있진 않습니다.

Rstudio -> tools -> Global Options -> General 에서 폴더 설정해주시면 되구요.

설치가 잘 안되신다면, Package 창에서 설치를 혹시 해보셨나요?

해당 부분은 p160 에 있습니다.
