### ISSUE TITLE
한글  분석을 위해 KoNLP를 Install하고,

### ISSUE THREAD

**Issue by newstars** [newstars/HelloR#14]
한글  분석을 위해 KoNLP를 Install하고,
 library(KoNLP) 눌렀을때, 다음 의 Error message 나타납니다.
해결하기 위해 다음의 절차를 진행해 보았는데, Error가 해결이 안됩니다.

1. Error 메시지
Error: package or namespace load failed for ‘KoNLP’:
 .onLoad가 loadNamespace()에서 'rJava'때문에 실패했습니다:
  호출: inDL(x, as.logical(local), as.logical(now), ...)
  에러: unable to load shared object 'C:/Users/USER/Documents/R/win-library/3.6/rJava/libs/x64/rJava.dll':
  LoadLibrary failure:  지정된 모듈을 찾을 수 없습니다.

(해결 노력)
### 1. Java PGM 다운로드 들어가서, Version 8 Updating 211 버젼 다운로드 설치 완료함.
PGM명 :   JavaSetup8u211

### 2. RStudio로 돌아가서,
> install.packages("rJava") 실시
---> package ‘rJava’ successfully unpacked and MD5 sums checked가 나타나는데, 다음의 Warning이
       나타남.

WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/USER/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/rJava_0.9-11.zip'
Content type 'application/zip' length 831952 bytes (812 KB)
downloaded 812 KB

package ‘rJava’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\USER\AppData\Local\Temp\RtmpUbsi9F\downloaded_packages

### 3.library(rJava) 누르면, 다음의 메시지 나타남.

> library(rJava)
Error: package or namespace load failed for ‘rJava’:
 .onLoad가 loadNamespace()에서 'rJava'때문에 실패했습니다:
  호출: inDL(x, as.logical(local), as.logical(now), ...)
  에러: unable to load shared object 'C:/Users/USER/Documents/R/win-library/3.6/rJava/libs/x64/rJava.dll':
  LoadLibrary failure:  지정된 모듈을 찾을 수 없습니다.

---> Java를 설치했는데, 왜 Error가 나타나는지요 ?

### 4. library(KoNLP) 를 눌러도, 다음의 동일한 메시지 나타남.

> library(KoNLP)
Error: package or namespace load failed for ‘KoNLP’:
 .onLoad가 loadNamespace()에서 'rJava'때문에 실패했습니다:
  호출: inDL(x, as.logical(local), as.logical(now), ...)
  에러: unable to load shared object 'C:/Users/USER/Documents/R/win-library/3.6/rJava/libs/x64/rJava.dll':
  LoadLibrary failure:  지정된 모듈을 찾을 수 없습니다.

-----> 인터넷의 Error 해결 가이드대로 해도 안됩니다.
          도움 부탁드립니다.

_Originally posted by @jooseokkim in https://github.com/newstars/HelloR/issues/12#issuecomment-491473374_

**Comment by newstars** [comment]
안녕하세요. 

KoNLP가 최신 패키지가 아니라서 완전 최신 버전에서는 문제가 좀 있는듯 합니다.
https://cran.r-project.org/web/packages/KoNLP/vignettes/KoNLP-API.html

github에 있는 설치방법으로 진행해보시길 바랍니다.
https://github.com/haven-jeon/KoNLP

문서상에 있는 버전을 맞춰서 진행해보시는것이 좋을듯 하네요.
https://github.com/haven-jeon/KoNLP/blob/master/DESCRIPTION

**Comment by jooseokkim** [comment]
강준희님.
​
설치 error를 어떻게 해결해야 합니까?
좀 도와 주세요.
​
아니면 한글 형태소 분석하려면 다른 package가 있나요?
​
-----Original Message-----

**Comment by newstars** [comment]
안녕하세요. 강전희 입니다.

은전한잎 프로젝트가 있긴 한데, 저도 써보진 않았습니다.

https://github.com/NamyounKim/NLP4kec
