### ISSUE TITLE
교재p60에 "리스트"가 다음과 같이 표현되는 이유 설명 부탁드립니다. 

### ISSUE THREAD

**Issue by ruby-Jeong** [newstars/HelloR#16]
교재p60에 "리스트"가 다음과 같이 표현되는 이유 설명 부탁드립니다.
리스트: {벡터, 배열, 데이터 프레임, 리스트} 

감사합니다^^

**Comment by newstars** [comment]
안녕하세요.

리스트는

벡터, 행렬, 배열, 데이터 프레임 등과 같은 다른 데이터 구조도 모두 리스트로 묶을 수 있습니다.

감사합니다.
