### ISSUE TITLE
에러가 왜 나는 것인지 알고 싶습니다.

### ISSUE THREAD

**Issue by eylees** [newstars/HelloR#17]
처음시작하는 R 데이터분석 책의 p84~85 실습 중 자꾸 에러가 납니다.
책 본문과 똑같이(단, Rstudy폴더를 d드라이브에 설정함) 코딩했는데요.
왜 그런지 답답합니다.

코딩
ex_data1<-read.table('d:/Rstudy/data_ex.txt',header=TRUE)
View(ex_data1)
ex_data2<-read.table('d:/Rstudy/data_ex.txt',header=TRUE,skip=2)
View(ex_data2)

에러내용
> ex_data1<-read.table('d:/Rstudy/data_ex.txt',header=TRUE)
Error in type.convert.default(data[[i]], as.is = as.is[i], dec = dec,  : invalid multibyte string at '<ec><84><9c>?<b8>'
> View(ex_data1)
Error in View : object 'ex_data1' not found
> ex_data2<-read.table('d:/Rstudy/data_ex.txt',header=TRUE,skip=2)
Error in type.convert.default(data[[i]], as.is = as.is[i], dec = dec,  : 
  invalid multibyte string at '<ec><a0><9c>二<bc>'
> View(ex_data2)
Error in View : object 'ex_data2' not found

**Comment by newstars** [comment]
안녕하세요. 

인코딩 문제인듯 합니다.

ex_data1<-read.table('d:/Rstudy/data_ex.txt',header=TRUE, fileEncoding = "euc-kr")

와 같은 형태로 인코딩 설정 해보세요.
