### ISSUE TITLE
r studio에서 source on save가 무엇인지 궁금합니다.

### ISSUE THREAD

**Issue by ruby-Jeong** [newstars/HelloR#18]
안녕하세요^^

r studio에서 저장하기 버튼 옆에 있는
"source on save"가 무엇인지 궁금합니다.

감사합니다.

**Comment by newstars** [comment]
안녕하세요.

"source on save" 는 함수나 변수를 저장하여 재사용하기 위한 기능입니다.

이것을 체크하면 소스파일이 저장되고, R의 전역 변수 혹은 전역 함수로 기록됩니다.

정리가 잘되어 있는 아래 블로그를 참고하시면 좋을듯 합니다.
http://blog.naver.com/PostView.nhn?blogId=lingua&logNo=220491053750

감사합니다.
