### ISSUE TITLE
data.frame(ID, SEX, AGE, AREA)와 data.frame(ID=ID, SEX=SEX, AGE=AGE, AREA=AREA)는 같은 것인가요?

### ISSUE THREAD

**Issue by ruby-Jeong** [newstars/HelloR#19]
안녕하세요^^ 

교재 P70에서 데이터 프레임을 만들 때는 data.frame(ID, SEX, AGE, AREA)으로 나와 있지만, 
교재 p80에서는data.frame(ID=ID, SEX=SEX, AGE=AGE, AREA=AREA)와 같은 형식으로 나와있습니다.

그 이유가 궁금합니다.
실제로 해보니, 두 방법의 결과가 같은 것 같은데, 
두 방법이 같은 것인가요?

감사합니다.

**Comment by newstars** [comment]
안녕하세요.

두 방법은 실제 결과값은 같습니다.

data.frame(ID=ID, SEX=SEX, AGE=AGE, AREA=AREA)
위와 같은 방법은 열의 이름을 정하여 주는 방법이며,

열 이름을 따로 지정하지 않을 경우에는, 변수명을 열 이름으로 생성되게 됩니다.
data.frame(ID, SEX, AGE, AREA)

예시로,
data.frame(ID=SEX, SEX=AGE, AGE=AREA, AREA=ID) 와 같은 형태로 바꿔서 입력해보시면 될듯 합니다.

감사합니다.
