### ISSUE TITLE
안녕하세요! 질문이 있습니다. 

### ISSUE THREAD

**Issue by hn8368hn** [newstars/HelloR#2]
안녕하세요 ^^ 
처음 시작하는 R 데이터분석 책을 사서 공부하고 있는 취준생입니다!
이 책 한 권만으로 공부하는데도 굉장히 큰 도움을 받고 있습니다 ㅎㅎ 

다른게 아니라 질문이 있는데 요 ㅜㅜ 
패키지 불러올 때 가끔 오류가 뜹니다. 
지식인에서도 해결하기 어렵고 ,, 외국 사이트에서는 R의 버젼에 따라 오류가 있을 수도 있다고 합니다.
제 R 버젼은 3.5.1 입니다. 
가능하면 사진도 올리고 싶은데 사진은 올리는 방법을 모르겠네요 ㅜㅜ 

코드 입력은 

install.packages("descr")
library(descr)

입력하고, 설치까지는 잘 되는데 library만 실해하면 'descr'이라고 불리는 패키지가 없습니다. 이런 오류가 계속 뜹니다 ㅜㅜ 
확인 한 번만 부탁드립니다 ㅜㅜ 감사합니다.

**Comment by newstars** [comment]
안녕하세요. 혹시 어떤 에러인지 알려주실 수 있나요?

newstars77@gmail.com 로 사진 보내주세요. 확인 해보도록 하겠습니다.

**Comment by newstars** [comment]
안녕하세요. 

라이브러리 경로를 제대로 못찾는 듯 합니다.

.libPaths() 라는 함수를 실행하시면, R 라이브러리가 설치되어 있는 경로를 확인할 수 있습니다.

해당 경로를 확인해보세요.

저 같은 경우는 "C:\Users\newst\Documents\R\win-library\3.5" 입니다.
> .libPaths()
[1] "C:/Users/newst/Documents/R/win-library/3.5" "C:/Program Files/R/R-3.5.1/library"  

해당 경로가 아닐 경우 라이브러리 설정 방법은 다음과 같습니다.
.libPaths("C:/Users/newst/Documents/R/win-library/3.5")

그리고 조금 쉽게 할수 있는 방법은 R 스튜디오의 오른쪽 하단에 있는 Packages 패널을 활용하는 것입니다.

책 160페이지를 참고하시면 됩니다.

감사합니다.
