### ISSUE TITLE
그래프 관련 에러입니다.

### ISSUE THREAD

**Issue by Jonggeonkim** [newstars/HelloR#20]
수고 많으십니다.
검토해 주세요..

1. library(readxl)
exdata1 <- read_excel("M:/Rstudy/Sample1.xlsx")
exdata1
hist(exdata1$AGE)

Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'C:/Users/??????/AppData/Local/Temp/RtmpojC6hk/rs-graphics-719823bc-0a19-429c-b67a-29291d0af492/b4e027e4-16b8-4df6-9b4d-4998ae0be812.snapshot', probable reason 'Invalid argument'
Graphics error: Plot rendering error

2. hist(exdata1$AGE, xlim = c(0,60),ylim = c(0,5),main="AGE분포")

Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'C:/Users/??????/AppData/Local/Temp/RtmpojC6hk/rs-graphics-719823bc-0a19-429c-b67a-29291d0af492/891a1819-8e0b-4f12-af92-881039997d36.snapshot', probable reason 'Invalid argument'
Graphics error: Plot rendering error

3. install.packages("descr")
library(descr)
freq(exdata1$SEX, plot = T, main='성별(barplot')

      Frequency Percent
F             6      60
M             4      40
Total        10     100
Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'C:/Users/??????/AppData/Local/Temp/RtmpojC6hk/rs-graphics-719823bc-0a19-429c-b67a-29291d0af492/6840514b-7e46-475f-ba50-a2e86de267e8.snapshot', probable reason 'Invalid argument'
Graphics error: Plot rendering error

4. dist_sex <- table(exdata1$SEX)
dist_sex
barplot(dist_sex)

Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'C:/Users/??????/AppData/Local/Temp/RtmpojC6hk/rs-graphics-719823bc-0a19-429c-b67a-29291d0af492/c47ab58b-0fca-43b7-a3ce-31377fb80748.snapshot', probable reason 'Invalid argument'
Graphics error: Plot rendering error

5. barplot(dist_sex, ylim = c(0,8)) 

Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'C:/Users/??????/AppData/Local/Temp/RtmpojC6hk/rs-graphics-719823bc-0a19-429c-b67a-29291d0af492/876a2829-89cb-4269-af10-0bc56f82c27d.snapshot', probable reason 'Invalid argument'
Graphics error: Plot rendering error

6. barplot(dist_sex, ylim = c(0,8),main = "BARPLOT",xlab = "SEX",
        ylab="FREQUENCY",names=c("Female","Male")) 

Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'C:/Users/??????/AppData/Local/Temp/RtmpojC6hk/rs-graphics-719823bc-0a19-429c-b67a-29291d0af492/3fa7d776-3d06-42b0-8af0-87b83505b7fa.snapshot', probable reason 'Invalid argument'
Graphics error: Plot rendering error

7. barplot(dist_sex, ylim = c(0,8),main = "BARPLOT",xlab = "SEX",
        ylab="FREQUENCY",names=c("Female","Male"),col=c("pink","navy"))

Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'C:/Users/??????/AppData/Local/Temp/RtmpojC6hk/rs-graphics-719823bc-0a19-429c-b67a-29291d0af492/e59f725e-83c1-4785-8061-7ec877c71a86.snapshot', probable reason 'Invalid argument'
Graphics error: Plot rendering error

8. library(readxl)
exdata1 <- read_excel("M:/Rstudy/Sample1.xlsx")
exdata1
boxplot(exdata1$Y17_CNT,exdata1$Y16_CNT)

Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'C:/Users/??????/AppData/Local/Temp/RtmpojC6hk/rs-graphics-719823bc-0a19-429c-b67a-29291d0af492/bee16290-77b4-4ace-8f02-7532663f4bd4.snapshot', probable reason 'Invalid argument'
Graphics error: Plot rendering error

9, boxplot(exdata1$Y17_CNT,exdata1$Y16_CNT,ylim=c(0,60),main="boxplot",
        names=c("17년 건수","16년 건수"))

Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'C:/Users/??????/AppData/Local/Temp/RtmpojC6hk/rs-graphics-719823bc-0a19-429c-b67a-29291d0af492/de0f1b2d-72f5-4663-9164-f9ffc047975a.snapshot', probable reason 'Invalid argument'
Graphics error: Plot rendering error

10, boxplot(exdata1$Y17_CNT,exdata1$Y16_CNT,ylim=c(0,60),main="boxplot",
        names=c("17년 건수","16년 건수"),col=c("green","yellow"))

Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'C:/Users/??????/AppData/Local/Temp/RtmpojC6hk/rs-graphics-719823bc-0a19-429c-b67a-29291d0af492/f47d92af-29e3-414e-8041-dafba21e104f.snapshot', probable reason 'Invalid argument'
Graphics error: Plot rendering error

11. y1 <- c(1,2,3,4,5,6,7,8,9,10,20,25)
boxplot(y1)

Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'C:/Users/??????/AppData/Local/Temp/RtmpojC6hk/rs-graphics-719823bc-0a19-429c-b67a-29291d0af492/4e2547a9-8aff-4471-a986-6a46473c4a5f.snapshot', probable reason 'Invalid argument'
Graphics error: Plot rendering error

수고하십시요.

**Comment by newstars** [comment]
안녕하세요. 강전희 입니다.

해당 이슈는 모두 경로를 찾지 못해서 발생하는 이슈 입니다.

실제 경로를 보시면 사용자 계정 부분이 전부다 ?????? 로 표기되는 걸 보실수 있습니다.

'C:/Users/??????/AppData/Local/Temp/'

영문으로 계정을 새로 생성하시거나,
지금 사용하시는 계정명을 영문으로 바꾸셔서 사용하셔야 합니다만,

MS에서는 영문 계정을 만들기를 권장하며, 계정명을 바꾸는 것은 권장하지 않는 방법입니다.

감사합니다.

**Comment by Jonggeonkim** [comment]
강선생님, 감사합니다. 
-----Original Message-----
