### ISSUE TITLE
패키지 관련 에러입니다.

### ISSUE THREAD

**Issue by Jonggeonkim** [newstars/HelloR#21]
안녕하세요.

기본 패키지 보기가 잘 안됩니다.

1. library(help="base")  

Error: File C:\Users\김종건\AppData\Local\Temp\RtmpojC6hk\RpackageInfo2dcc5e4670ec does not exist.

2.  library(help=datasets)

Error: File C:\Users\김종건\AppData\Local\Temp\RtmpojC6hk\RpackageInfo2dcc2e96189d does not exist.

3.  x<- c(9,15,20,6)
label<-c("영업1팀","영업2팀","영업3팀","영업4팀")
pie(x,labels=label,main="부서졀 영업 실적")

Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'C:/Users/??????/AppData/Local/Temp/RtmpojC6hk/rs-graphics-719823bc-0a19-429c-b67a-29291d0af492/e2cead9c-3f7c-46b5-8180-ff2269c0ba45.snapshot', probable reason 'Invalid argument'
Graphics error: Plot rendering error

4.  height<- c(9,15,20,6)
name<-c("영업1팀","영업2팀","영업3팀","영업4팀")
barplot(height,names.arg=name,main="부서졀 영업 실적",col=rainbow(length(height)),xlab="부서",
        ylab="영업실적(억 원)")

Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'C:/Users/??????/AppData/Local/Temp/RtmpojC6hk/rs-graphics-719823bc-0a19-429c-b67a-29291d0af492/ed1ffd76-bde1-4c64-834d-2646c04a557a.snapshot', probable reason 'Invalid argument'
Graphics error: Plot rendering error

5. install.packages("animation")
library(animation)

Installing package into ‘C:/Users/김종건/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/animation_2.6.zip'
Content type 'application/zip' length 545551 bytes (532 KB)
downloaded 532 KB

ani.options(interval=1)
plot.new()

for(i in 10:0){
  rect(0,0,1,1,col="yellow")
text(0.5,0.5,i,cex=5,col=rgb(.2,.2,.2,.7))
     ani.pause()
}

Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'C:/Users/??????/AppData/Local/Temp/RtmpojC6hk/rs-graphics-719823bc-0a19-429c-b67a-29291d0af492/2e44f18f-2bc8-4114-a02b-53d3e333c196.snapshot', probable reason 'Invalid argument'
Graphics error: Plot rendering error
Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'C:/Users/??????/AppData/Local/Temp/RtmpojC6hk/rs-graphics-719823bc-0a19-429c-b67a-29291d0af492/5f4d9833-5069-44f6-aafe-d1bb19cb525c.snapshot', probable reason 'Invalid argument'
Graphics error: Plot rendering error
Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'C:/Users/??????/AppData/Local/Temp/RtmpojC6hk/rs-graphics-719823bc-0a19-429c-b67a-29291d0af492/0bce47eb-3782-45a3-b0e1-f8e3598dc3a0.snapshot', probable reason 'Invalid argument'
Graphics error: Plot rendering error
Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'C:/Users/??????/AppData/Local/Temp/RtmpojC6hk/rs-graphics-719823bc-0a19-429c-b67a-29291d0af492/705bb32a-4b1e-4ba1-be00-1892a1679bcb.snapshot', probable reason 'Invalid argument'
Graphics error: Plot rendering error
Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'C:/Users/??????/AppData/Local/Temp/RtmpojC6hk/rs-graphics-719823bc-0a19-429c-b67a-29291d0af492/02fc5913-ae87-479f-86bb-90589ea37f81.snapshot', probable reason 'Invalid argument'
Graphics error: Plot rendering error
Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'C:/Users/??????/AppData/Local/Temp/RtmpojC6hk/rs-graphics-719823bc-0a19-429c-b67a-29291d0af492/440e5e20-aad3-42fc-a4f6-3d7ba42dd1df.snapshot', probable reason 'Invalid argument'
Graphics error: Plot rendering error
Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'C:/Users/??????/AppData/Local/Temp/RtmpojC6hk/rs-graphics-719823bc-0a19-429c-b67a-29291d0af492/669aa11f-e7bc-464f-a808-655cc34fa2ee.snapshot', probable reason 'Invalid argument'
Graphics error: Plot rendering error
Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'C:/Users/??????/AppData/Local/Temp/RtmpojC6hk/rs-graphics-719823bc-0a19-429c-b67a-29291d0af492/ca76f443-7abb-4646-949d-342a896a4454.snapshot', probable reason 'Invalid argument'
Graphics error: Plot rendering error
Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'C:/Users/??????/AppData/Local/Temp/RtmpojC6hk/rs-graphics-719823bc-0a19-429c-b67a-29291d0af492/f7f0f60d-aed5-477f-b129-37bba7526e62.snapshot', probable reason 'Invalid argument'
Graphics error: Plot rendering error
Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'C:/Users/??????/AppData/Local/Temp/RtmpojC6hk/rs-graphics-719823bc-0a19-429c-b67a-29291d0af492/fe263bed-dd82-452c-ab13-5f70fd2d391d.snapshot', probable reason 'Invalid argument'
Graphics error: Plot rendering error
Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'C:/Users/??????/AppData/Local/Temp/RtmpojC6hk/rs-graphics-719823bc-0a19-429c-b67a-29291d0af492/e8e5cdc1-2e54-4f60-85bc-7be9c6f411b6.snapshot', probable reason 'Invalid argument'
Graphics error: Plot rendering error

수고하세요.

**Comment by newstars** [comment]
안녕하세요.

이것도 앞에 달아주셨던 이슈랑 마찬가지로 한글 계정 관련 이슈입니다.

https://github.com/newstars/HelloR/issues/20

내용 참고하시면 될듯 합니다.

감사합니다.

**Comment by Jonggeonkim** [comment]
강성생님, 감사합니다.
 
해결됐습니다. 
-----Original Message-----
