### ISSUE TITLE
애니메이션 관련입니다.

### ISSUE THREAD

**Issue by Jonggeonkim** [newstars/HelloR#23]
안녕하세요?
애니메이션 공부하다가 에러 해결이 안됩니다.

1. <질문>
install.packages("animation")
library(animation)

ani.options(interval=1)
plot.new()

for(i in 10:0){
        rect((0,0,1,1,col="yellow")
        text(0.5,0.5,i, cex=5, col=rgb(.2,.2,.2,.7))
        ani.pause()
} 

     <결과>
    install.packages("animation")
Installing package into ‘C:/Users/prof/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/animation_2.6.zip'
Content type 'application/zip' length 545551 bytes (532 KB)
downloaded 532 KB

package ‘animation’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\prof\AppData\Local\Temp\RtmpM9JlVh\downloaded_packages
> library(animation)
> ani.options(interval=1)
> plot.new()
> 
> for(i in 10:0){
+         rect((0,0,1,1,col="yellow")
Error: unexpected ',' in:
"for(i in 10:0){
        rect((0,"
>         text(0.5,0.5,i, cex=5, col=rgb(.2,.2,.2,.7))
Error in as.graphicsAnnot(labels) : object 'i' not found
>         ani.pause()
> }        
Error: unexpected '}' in "}"

**Comment by newstars** [comment]
안녕하세요. 이건 오타네요.

에러 문구에 있는 것 처럼

 rect((0,0,1,1,col="yellow")

여기에 괄호 (( 2개가 들어가 있습니다.

질문이 상세하지도 않고 책에서 다루지 않는 부분까지는 답변 드리기 어렵습니다.

다음부터는 이슈 종료하겠습니다.
