### ISSUE TITLE
구글맵에 관한 의문입니다.

### ISSUE THREAD

**Issue by Jonggeonkim** [newstars/HelloR#24]
수고 많으십니다.
검토해 주십시요.

  <질문>
install.packages("ggplot2")
install.packages("RgoogleMaps")
install.packages("ggmap")
library(ggplot2)
library(RgoogleMaps)
library(ggmap)

names <- c("1.도담삼봉/석문","2.구담/옥순봉","3.사인암","4.하선암","5.중선암","6.상선암")
addr < - c("충청북도 단양군 매포읍 삼봉로 644-33",
           "충청북도 단양군 단성면 월악로 3827",
           "충청북도 단양군 대강면 사인암 2길 42",
           "충청북도 단양군 단성면 선암계곡로 1337",
           "충청북도 단양군 단성면 선암계곡로 868-2",
           "충청북도 단양군 단성면 선암계곡로 790")
gc <- geocode(enc2utf8(addr))
gc

df <- data_frame(name=names,lon=gc$loc, lat=gc$lat)
df

cen <- c(mean(df$lon),mean(df$lat))
cen

map <- get_googlemap(center = cen,
                     maptype = "roadmap",zoom=11,market=gc)

ggmap(map,fullpage = TRUE)

<결과>
   ...설치 부분 생략...
   library(ggplot2)
> library(RgoogleMaps)
> library(ggmap)
Google's Terms of Service: https://cloud.google.com/maps-platform/terms/.
Please cite ggmap if you use it! See citation("ggmap") for details.
> 
> names <- c("1.도담삼봉/석문","2.구담/옥순봉","3.사인암","4.하선암","5.중선암","6.상선암")
> addr < - c("충청북도 단양군 매포읍 삼봉로 644-33",
+            "충청북도 단양군 단성면 월악로 3827",
+            "충청북도 단양군 대강면 사인암 2길 42",
+            "충청북도 단양군 단성면 선암계곡로 1337",
+            "충청북도 단양군 단성면 선암계곡로 868-2",
+            "충청북도 단양군 단성면 선암계곡로 790")
Error: object 'addr' not found
> gc <- geocode(enc2utf8(addr))
Error in is.character(location) : object 'addr' not found
> gc
function (verbose = getOption("verbose"), reset = FALSE, full = TRUE) 
{
    res <- .Internal(gc(verbose, reset, full))
    res <- matrix(res, 2L, 7L, dimnames = list(c("Ncells", "Vcells"), 
        c("used", "(Mb)", "gc trigger", "(Mb)", "limit (Mb)", 
            "max used", "(Mb)")))
    if (all(is.na(res[, 5L]))) 
        res[, -5L]
    else res
}
<bytecode: 0x000002b86489aaf8>
<environment: namespace:base>
> 
> df <- data_frame(name=names,lon=gc$loc, lat=gc$lat)
Error in data_frame(name = names, lon = gc$loc, lat = gc$lat) : 
  could not find function "data_frame"
> df
function (x, df1, df2, ncp, log = FALSE) 
{
    if (missing(ncp)) 
        .Call(C_df, x, df1, df2, log)
    else .Call(C_dnf, x, df1, df2, ncp, log)
}
<bytecode: 0x000002b86489c238>
<environment: namespace:stats>
> 
> cen <- c(mean(df$lon),mean(df$lat))
Error in df$lon : object of type 'closure' is not subsettable
> cen
Error: object 'cen' not found
> 
> map <- get_googlemap(center = cen,
+                      maptype = "roadmap",zoom=11,market=gc)
Error in get_googlemap(center = cen, maptype = "roadmap", zoom = 11, market = gc) : 
  object 'cen' not found
> 
> ggmap(map,fullpage = TRUE)
Error in ggmap(map, fullpage = TRUE) : object 'map' not found
In addition: Warning message:
fullpage and expand syntaxes deprecated, use extent.

**Comment by newstars** [comment]
안녕하세요. 

문의 주신 부분은
이 역시도 에러 문구에 나와 있는 내용입니다.

Error: object 'addr' not found

코드에 띄어쓰기가 있네요.

addr < - c("충청북도 단양군 매포읍 삼봉로 644-33",

에러 문구에 원인이 나와있으니 참고하세요.
