### ISSUE TITLE
Chapter8 질문드립니다.

### ISSUE THREAD

**Issue by wjyang102** [newstars/HelloR#25]
install.packages("KoNLP")
library(KoNLP)
실행을 하면

> install.packages("KoNLP")
Installing package into ‘C:/Users/82106/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/KoNLP_0.80.1.zip'
Content type 'application/zip' length 5898744 bytes (5.6 MB)
downloaded 5.6 MB

package ‘KoNLP’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\82106\AppData\Local\Temp\Rtmp2refmd\downloaded_packages
> library(KoNLP)
Error: package or namespace load failed for ‘KoNLP’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 ‘Rcpp’이라고 불리는 패키지가 없습니다

이렇게 Rcpp가 없다는 오류가 뜹니다....
어떻게 해결하는게 좋을까요? ㅠㅠㅠ

**Comment by newstars** [comment]
안녕하세요. 혹시 별도로 RCPP를 설치 해보시고, 그래도 안되시는거면..

https://m.blog.naver.com/jjy0501/221300556843

이런 문제는 혹시 아니실까요...?
