### ISSUE TITLE
p189 관련 질문드립니다.

### ISSUE THREAD

**Issue by oluvie7** [newstars/HelloR#26]
해당 파트 교재 순서대로 진행하였는데요.
undata2 <- filter(function(x) { nchar(x) >= 2 }, undata)
이 부분을 입력해서 실행하면

Error in attr(data, "tsp") <- c(start, end, frequency) : 
  object is not a matrix
이라고 뜨면서 실행이 되지 않네요. 왜 그러는지 검색만으로는 알 수가 없어서 문의드립니다.

**Comment by newstars** [comment]
안녕하세요. 해당 부분은 오타라서 그렇습니다.

 filter(function(x) { nchar(x) >= 2 }, undata)

filter를 Filter 로 입력하시면 실행 되실꺼에요.

감사합니다.
