### ISSUE TITLE
p84 txt 파일 불러올 시에 한글 깨짐현상에 대해 문의드립니다 

### ISSUE THREAD

**Issue by nomadgamer123** [newstars/HelloR#27]
유튜브에도 댓글을 남기긴 했는데 github에도 재차 남겨봅니다.
utf-8 인코딩 설정을 하였는데도
View(ex_data)를 하면 한글이 깨져서 출력이 됩니다.
무엇이 문제일까요? 
![제목 없음](https://user-images.githubusercontent.com/55048217/69355349-f9a9ce80-0cc4-11ea-8f83-c341f5404a9e.png)

**Comment by newstars** [comment]
안녕하세요.
혹시 다운받은 파일은 제대로 보이시나요?
파일 다운로드가 제대로 안된 것처럼 보입니다.

https://www.youtube.com/watch?v=xs4cfVq5JQc

이 영상을 참고하시면 될듯 합니다.

감사합니다.

**Comment by nomadgamer123** [comment]
파일을 바로 열면 제대로 보이는데 R에서 열면 그렇습니다. readxl 을 이용해서 엑셀파일 열때는 문제 없었는데, read.table로 하면 한글이 깨져서 보이더군요

**Comment by newstars** [comment]
네 그런경우는 인코딩 이슈가 맞습니다.
그럴 경우 R 스튜디오에서 File창에서 txt 파일을 열어보시면 실제로도 깨져서 보이실꺼에요.

File > Reopen with encoding 메뉴에서 UTF-8로 정상적으로 보이신다면.

read.table("data_ex.txt", encoding="UTF-8") 옵션을 포함해서 저장하셔야 정상적으로 되실꺼에요.

**Comment by nomadgamer123** [comment]
이상합니다. Rstudio에서 file창에서 txt 파일을 열면 정상적으로 열립니다. 
ex_data <- read.table('C:/Rstudy/helloR/data/data_ex.txt')
View(ex_data)
그런데 이렇게 코드를 실행시키면 깨지네요.

**Comment by nomadgamer123** [comment]
아아,  encoding='UTF-8'을 넣으니 이제 정상적으로 켜집니다. 감사합니다

**Comment by newstars** [comment]
넵 다행이네요. 즐거운 공부되세요!

**Comment by nomadgamer123** [comment]
참 골치아프네요..  ex_data <- read.table('C:/Rstudy/helloR/data/data_ex.txt',  header = TRUE, encoding= 'UTF-8')
header = TRUE를 넣으면 또 에러가 납니다.

**Comment by nomadgamer123** [comment]
왜 자꾸 오류가 나는지 모르겠습니다 ㅠ 
x1_data <- read.table('C:/Rstudy/helloR/data/data_ex1.txt', sep=',', header = TRUE, fileEncoding = 'UTF-8') 입력하면 
Warning messages:
1: In read.table("C:/Rstudy/helloR/data/data_ex1.txt", sep = ",", header = TRUE,  :
  invalid input found on input connection 'C:/Rstudy/helloR/data/data_ex1.txt'
2: In read.table("C:/Rstudy/helloR/data/data_ex1.txt", sep = ",", header = TRUE,  :
  'C:/Rstudy/helloR/data/data_ex1.txt'에서 readTableHeader에 의하여 발견된 완성되지 않은 마지막 라인입니다 
오류가 뜹니다

**Comment by newstars** [comment]
invalid input found on input connection 의 경우에는 txt 파일이 UTF-8 이 아닐 가능성이 높습니다.

메모장으로 열고 다른이름으로 저장할때 인코딩 옵션을 UTF-8로 하시거나.
위에서 말한것처럼 R 스튜디오의 File > Reopen with encoding 메뉴에서 txt 파일을 열고 하단의 Set as default encoding for source files 를 체크하고 저장을 해주세요.

**Comment by nomadgamer123** [comment]
UTF-8과 UTF-8(BOM)은 아예 다른건가요?

**Comment by newstars** [comment]
넵 다른 형식입니다.

다음글을 참고하시면 좋겠네요.
http://blog.wystan.net/2007/08/18/bom-byte-order-mark-problem

**Comment by nomadgamer123** [comment]
감사합니다 선생님~
