### ISSUE TITLE
C:/  경로를 어떻게 선택하는 건가요?? [

### ISSUE THREAD

**Issue by minjae47** [newstars/HelloR#28]
C:/  경로를 어떻게 선택하는 건가요?? [...]버튼을 누르면 컴퓨터 내 파일 찾는 창으로 옮겨져서 어떻게 해야될지를 모르겠습니다.ㅠㅠ

**Comment by newstars** [comment]
자세한 설정은 유튜브를 참고하시면 좋을듯 합니다.

https://www.youtube.com/watch?v=6WSHAFDj2-E&
