### ISSUE TITLE
Rank 함수 - 순위가 소수점?

### ISSUE THREAD

**Issue by oriiiii** [newstars/HelloR#29]
안녕하세요.
챕터9 203페이지의 rank 함수 관련 질문 드려요.
책 예시를 보면 mpg_rank 열에 mpg의 순위가 나오는데
순위가 19.5, 24.5 등 소수점으로 나옵니다.
일반적으로 순위라면 1등 2등 이렇게 정수로 끊어지는 게 맞는 거 같은데
여기서 말하는 순위는 다른 개념인지요?

**Comment by newstars** [comment]
안녕하세요. 답변이 늦었습니다.

공동 순위인 것들이 소수점으로 표기된 부분입니다.

rank()함수의 경우 기준에 따라서 여러가지로 나눠져 있습니다.

dplyr 패키지에 포함되어 있으며, 대략 2가지만 소개하도록 하겠습니다.

동일값이어도 index 순위대로 지정하는 row_number() 함수,

동률일 경우에 같은 순위로 평가하기 위해서는 min_rank() 함수 등이 있습니다.

예시는 base R 로 진행된 것입니다.

감사합니다.

**Comment by oriiiii** [comment]
답변 감사 드립니다.
-----Original Message-----
