### ISSUE TITLE
챕터 04 read.table() 함수 에러

### ISSUE THREAD

**Issue by fodud1020** [newstars/HelloR#31]
교재 83쪽 데이터 가져오기 부분에서 교재와 같이 입력을 하면 에러가 뜨데요 다음과 같습니다.

> ex_data <- read.table("C:/Users/jraey/Downloads/HelloR-master/Data/data_ex.txt")
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 1 did not have 5 elements

5개의 엘레멘트가 없다고 나오는데 어떻게 해야하나요?

**Comment by newstars** [comment]
안녕하세요. 텍스트 파일의 문제일듯 합니다.

라인1이 5개의 원소가 안되어서 생기는 문제인데, 이건 txt 파일을 확인해봐야할듯 합니다.

혹시 파일 가져오기 내용은
https://www.youtube.com/watch?v=fb4Sp2IYbxo
이 영상을 참고하시면 됩니다.

감사합니다.
