### ISSUE TITLE
아무 것도 건드리지 않았는데 에러: 객체 00를 찾을 수 없습니다' 가 뜹니다.

### ISSUE THREAD

**Issue by JIWONRSUDY** [newstars/HelloR#32]
안녕하세요. 어제 책을 구입해서 혼자 공부하고 있는 학생입니다.
R과 R 스튜디오 모두 다운로드 해서 시도해보고 있는데, 처음부터 에러 창이 뜨니 막막해서 질문글을 남겨봅니다.

이미지 : https://user-images.githubusercontent.com/61136033/74629510-bcf25400-519b-11ea-9842-ba5f3792cd04.png
( ![image](https://user-images.githubusercontent.com/61136033/74629510-bcf25400-519b-11ea-9842-ba5f3792cd04.png) )

아래 이미지와 같이 계속 '에러: 객체 000를 찾을 수 없습니다.' 가 뜹니다. 기본 사칙연산 (1+2)은 잘 계산되어 콘솔창에 뜨는데, 변수 생성만 하면 어떤 알파벳이든 모두 에러가 뜹니다. 검색해봐도 해결이 안되어서 답답하네요...  확인 부탁드립니다!

**Comment by newstars** [comment]
안녕하세요. 

오른쪽 상단의 환경창에 봤을 때 코드가 아무것도 실행이 되지 않은 듯 합니다.

작성하신 코드를 한줄씩 실행하시거나, 전체를 드레그 하셔서 실행하시면 될듯 합니다.

감사합니다.
