### ISSUE TITLE
맥에서 treemap 사용시 한글 깨짐

### ISSUE THREAD

**Issue by naruto4994** [newstars/HelloR#33]
안녕하세요. 맥북 사용자입니다. 

treemap 사용할 때 한글 깨짐 현상을 앞에 말씀해주신 도움말 ( `fontfamily.labels="AppleGothic" `) 통해서 거의 해결했는데요, 아직 title만은 계속 ㅁㅁㅁㅁ으로 깨져서 나옵니다. 

혹시 이 문제를 해결할 방법이 있을까요? 
아래 그림 파일이 결과물입니다. 

![image](https://user-images.githubusercontent.com/64573202/80673228-b9f3d800-8ae9-11ea-90b3-9c6880014115.png)

**Comment by newstars** [comment]
안녕하세요. 

제목은 fontfamily.title 옵션을 사용하시면 됩니다.

fontfamily.title = "AppleGothic"

감사합니다.
