### ISSUE TITLE
직관적인 메뉴로 원리 데이터 가져오기 문의

### ISSUE THREAD

**Issue by Bestworld7** [newstars/HelloR#35]
책 페이지 88에 직관적인 메뉴로 원시 데이터 가져 오기 실행 시 
![직관적](https://user-images.githubusercontent.com/64624958/80778908-e91b4f80-8ba4-11ea-8c14-1aaa710b2ef9.JPG)

상기와 같이 에러가 발생하는데 제가 설정을 잘못한 것인가요?
엑셀은 파일 명이 "너무 길어요" 이런 메세지가 나타납니다. 

문제를 해결하고 싶은데 찾아볼 곳이 없어 문의 드립니다.

**Comment by Bestworld7** [comment]
파일을 불러오는 경로명을 수정하니 해결이 되네요 
파일경로에 "_"와 "한글"이 있어서 안되었던 것 같습니다. 
유튜브에 경로명에 대한 설명을 추가해 주시면 도움이 될 것 같습니다....

**Comment by newstars** [comment]
의견감사합니다.
