### ISSUE TITLE
Psych설치

### ISSUE THREAD

**Issue by jeongyeonlee123** [newstars/HelloR#36]
![F214ED63-ACB8-4EBB-A10E-3C6D52232618](https://user-images.githubusercontent.com/67193191/85202084-ec2df300-b33e-11ea-8729-ba05d8955c09.jpeg)
패키지 psych를 설치하려고 하고 확인하는데 안되는데 어떻게 해야 하나요??

**Comment by newstars** [comment]
안녕하세요
패키지 설치는 install.packages("Psych") 입니다.
