### ISSUE TITLE
googlevis

### ISSUE THREAD

**Issue by wallow11** [newstars/HelloR#38]
책 234페이지
googlevis. ggmap. 
를 따라하는데
plot()
실행 이후에 아무런 변화가 없습니다
크롬 adobe flash player 옵션도 바꿔봤는데
chart가 안보입니다
plot() 실행이후 아무런 변화가 없습니다
어떻게 하면 chart가 보일까요?

**Comment by newstars** [comment]
안녕하세요. 답변이 늦었습니다.

우선 googlevis 문제는 크롬 Flash 문제로 예상되긴 합니다.

flash에서 http // https 관련 문제로 예상되긴 합니다.

googlevis 에서도 동일한 문제로 issue 가 등록되어 있네요.
https://github.com/mages/googleVis/issues/89

다른 공식 문서에서도 flash 관련 내용이 보입니다.
https://cran.r-project.org/web/packages/googleVis/googleVis.pdf

현재로서는 수정될때까지 시간이 필요할 듯 합니다.

감사합니다.
