### ISSUE TITLE
안녕하세요, 책보면서 따라하다가 오류가 나서 질문드립니다.

### ISSUE THREAD

**Issue by GePP-918** [newstars/HelloR#39]
KoNLP패키지 설치 후

 library(KoNLP)
 useSystemDic()
 useSejongDic()
 useNIADic()

이걸 실행하는 과정에서

SejongDic 이랑 NIADic은 잘 실행되는데

 SystemDic만

Backup was just finished!
Error in `[.data.frame`(result_dic, , 2) : undefined columns selected

이렇게 오류가 떠서 진행이 되지 않습니다.. 도와주세요.

**Comment by newstars** [comment]
안녕하세요. 혹시 사용중인 버전들을 알수 있을까요?

에러 자체는 "명확하지 않은 칼럼을 선택했다" 라고 되어있는데,

최근 KoNLP 패키지가 CRAN에서 내려가져 있어서 정상적이진 않습니다..

https://github.com/haven-jeon/KoNLP/issues/59

**Comment by GePP-918** [comment]
감사합니다.운영체제는 10
R은 4. 0. 2
R 스튜디오는 4. 0. 2에 x86_64-w64-mingw32/x64 (64-bit)
입니다(죄송합니다 잘 알지 못해서)
 
 
 
-----Original Message-----

**Comment by GePP-918** [comment]
참 213p에 gglpot(airquality, aes(x = Day, y = Temp))
이렇게 설명 나와있는데 오타같네요. 오류가 나고
 
 gglpot(airquality, aes(x = 'Day', y = 'Temp')) 
이렇게 해보니 정상실행됩니다. 감사합니다.
-----Original Message-----

**Comment by GePP-918** [comment]
안녕하세요.  제가 2번째로 보내드린 오타 문의가
단순히 변수 대문자구분때문에 발생한 오류였네요. ㅠㅠ 'Day', 'Temp' 이렇게 하니 geom_point()가 적용이 안되네요.
그냥 못들은걸로 해주세요... 감사합니다.
 
 
-----Original Message-----
