### ISSUE TITLE
교제 85페이지 예제 질문 드립니다.

### ISSUE THREAD

**Issue by hmyang9223** [newstars/HelloR#4]
ex_data2 <- read.table("C:/Rstudy/data_ex.txt", header = TRUE, skip = 2) 항목에서 

만약 제가 ID, SEX, AGE, AREA를 남기면서 1,2행을 지우고자 한다면 어떤식으로 해야 하는지요?
현재는 skip 2가 들어가면서 2번째 행이 변수명으로 지정되고 3행이 첫행으로 되어있는 
형태라서요.

**Comment by newstars** [comment]
안녕하세요. 강전희 입니다.

우선 한번에 처리 하기엔 read.table() 함수에서 해당 옵션을 제공하지 않아 어렵습니다.

**1안**
header를 수작업으로 처리 하는 가장 쉬운 방법이 있구요.
header <- c("ID", "SEX", "AGE", "AREA")
ex_data <- read.table("data_ex.txt", header=TRUE, skip=2, col.names = header)

**2안**
파일에서 header를 따로 저장해서 입력하는 방법
header <- read.table("data_ex.txt", nrows = 1)
ex_data2 <- read.table("data_ex.txt", skip=2)
colnames(ex_data2) <- unlist(header)

**3안**
index에서 제거 하는 방법
data2 <- read.table('data_ex.txt', header =TRUE)[-1:-2,]

**4안**
dplyr 패키지의 slice()함수로 추출하는 방법
library(dplyr)
data3 <- read.table('data_ex.txt', header=T) %>% slice(-1:-2)

여러 방법이 있으니 편하신대로 사용하시면 될듯 합니다.

감사합니다.

**Comment by hmyang9223** [comment]
네 아무래도 가장 쉬운 첫번째가 저에게 맞는 것 같습니다. 감사합니다.
