### ISSUE TITLE
readxl 설치 오류

### ISSUE THREAD

**Issue by hyeppy321** [newstars/HelloR#40]
안녕하세요
패키지 설치가 안되는데 사용자명이 한글이여서 그런 것 같아요
사용자 만드는 것 말고 방법이 있을까요?

**Comment by newstars** [comment]
안녕하세요.
R에서는 한글 경로가 인식이 안되기 때문에 그런문제가 있는데 경로를 변경해서 설치하시면 됩니다.

> .libPaths()
으로 설치 경로를 확인하실 수 있고

> .libPaths("d:/rstudy)
등으로 경로를 변경하실수 있습니다.

감사합니다.

**Comment by hyeppy321** [comment]
감사합니다 ◡̈ 

​
-----Original Message-----
