### ISSUE TITLE
실습 폴더 설정 중 에러가 발생합니다.

### ISSUE THREAD

**Issue by goaxhfdl231** [newstars/HelloR#41]
![질문](https://user-images.githubusercontent.com/69578152/89998026-f679c700-dcc7-11ea-933f-478c7640f0c7.PNG)

처음 시작하는 r데이터 분석 책 38p에서 실습 폴더 생성 따라하다가

``` 클릭 후 C 눌렀는데 몇 초 뒤에 제가 첨부한 사진처럼 에러가 발생했다고 계속 뜹니다. ㅠㅠ
프로그램을 껐다 켜도 그대로여서 질문 남기고 갑니다.. ㅠㅠ

**Comment by newstars** [comment]
안녕하세요. R 스튜디오의 문제인듯 합니다.

완전히 다 (폴더까지) 지우고 다시 설치 해보시고, 그래도 안되면 다른 버전으로 해보셔야 될꺼 같습니다.

https://stackoverrun.com/ko/q/13087514
https://community.rstudio.com/t/r-encountered-a-fatal-error-the-session-was-terminated/32754/3
https://community.rstudio.com/t/r-encountered-a-fatal-error-the-session-was-terminated/6409/2
