### ISSUE TITLE
Mac 한글 깨짐 문의

### ISSUE THREAD

**Issue by pufs1379** [newstars/HelloR#42]
맥에서 테스트중인데 page.83 
read.table 로 txt  파일 불러오면 한글이 깨집니다.

글로벌 인코딩 세팅은 UTF-8 로 설정하였습니다. 

<img width="361" alt="스크린샷 2020-09-29 오전 11 21 36" src="https://user-images.githubusercontent.com/1892450/94505416-046ab380-0246-11eb-9185-2ee32555559e.png">

**Comment by newstars** [comment]
안녕하세요. 

제가 자주 못들어오다보니 이슈가 있는걸 놓쳤네요.

죄송합니다.

파일의 인코딩 이슈인데요.

read.table() 함수에 fileEncoding="utf-8" 옵션으로 처리하시면 됩니다.

감사합니다.
