### ISSUE TITLE
p.203과 p.210 에 연비별 순위 오류

### ISSUE THREAD

**Issue by PHDcandidate** [newstars/HelloR#43]
mpg 는 mile per gallon 으로 연비죠.  1갤런으로 갈 수 있는 마일 수니까 높을 수록 연비가 좋다는 겁니다.
즉, mpg의 숫자가 클수록, mpg_rank의 숫자는 작아야 하니까 반비례 관계로
rank(-mpg)처럼 negative로 설정되는 것이 맞습니다.

> mutate(mtcars, mpg_rank=rank(-mpg)) %>% arrange(mpg_rank)
    mpg cyl  disp  hp drat    wt  qsec vs am gear carb mpg_rank
 33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1      1.0
32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1      2.0
30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2      3.5
30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2      3.5
27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1      5.0

아주 많은 도움이 되고 있습니다.
다음 쇄에서는 수정되길 바라는 마음입니다.

**Comment by newstars** [comment]
안녕하세요. 

확인이 늦었습니다.

좋은 지적 감사합니다.

반영할 수 있도록 하겠습니다.

감사합니다.
