### ISSUE TITLE
질문 드립니다 (p.92~93)

### ISSUE THREAD

**Issue by HyunSeunghwan** [newstars/HelloR#44]
안녕하세요?
유튜브 강의와 책을 보며 혼자서 R프로그래밍을 독학하고 있습니다.
p92에 소개된 바와 같이 Rstudio 메뉴 기능을 활용해서 엑셀 파일을 불러오려고 하는데, 계속 에러가 나서 문의드립니다.
![image](https://user-images.githubusercontent.com/87059940/124712105-d84d3300-df39-11eb-998b-428d074d2f1c.png)
위 사진과 같이 에러가 나는 이유가 무엇이고, 해결책이 무엇인지 문의드립니다.

**Comment by newstars** [comment]
안녕하세요. 해당 오류는 경로가 한글이어서 그렇습니다.

실제 오류나는 부분과, 파일 경로를 매칭시켜보시면 쉽게 확인하실 수 있습니다.

대부분의 프로그래밍 언어들에서는 영문 경로를 사용하시는 것이 좋습니다.

감사합니다.
