### ISSUE TITLE
7장 p168 질문 드립니다

### ISSUE THREAD

**Issue by HyunSeunghwan** [newstars/HelloR#45]
좋은 영상(유튜브) 강의를 제공해 주셔서 감사합니다.
p168 실습을 하다보니, 그대로 코딩을 따라했는데도 불구하고,
melt_test<-melt(airquality)를 실행했을 때
No id variables; using all as measure variables
Error in melt_dataframe(data, as.integer(id.ind - 1), as.integer(measure.ind -  : 
  function 'Rcpp_precious_remove' not provided by package 'Rcpp'
창이 뜨면서 그 밑에 있는 과정도 진행이 되지 않습니다.

에러가 뜨는 원인이 무엇일까요?

**Comment by newstars** [comment]
안녕하세요. 

해당 코드가 워낙 짧아서 코드 전체를 봐야할꺼 같긴한데요.

No id variables; using all as measure variables 의 경우에는 
melt() 함수 특성상 숫자가 있는 모든 칼럼을 value 변수라고 보기때문에 발생되는 문구입니다.

R 3.* 나 R 4.* 에서도 전 발생되지 않고 있네요.

코드 전체를 올려주실수 있으신가요?
