### ISSUE TITLE
81쪽 readxl 패키지 설치부터가 잘 안됩니다 ㅠㅠ

### ISSUE THREAD

**Issue by Kuuaba** [newstars/HelloR#46]
install.packages("readxl")
library(readxl)을 입력하면 
install.packages("readxl")
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
‘C:/Users/User/Documents/R/win-library/4.1’의 위치에 패키지(들)을 설치합니다.
(왜냐하면 ‘lib’가 지정되지 않았기 때문입니다)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/readxl_1.3.1.zip'
Content type 'application/zip' length 1717469 bytes (1.6 MB)
downloaded 1.6 MB

package ‘readxl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Public\Documents\ESTsoft\CreatorTemp\RtmpiGQgi7\downloaded_packages
이렇게 뜨고 나서뒤에 데이터세트 저장부터 하려고하면
> excel_data_ex<-read_excel("C:/Rstudy/data_ex/xls")
Error in read_excel("C:/Rstudy/data_ex/xls") : 
  could not find function "read_excel"이렇게 뜨네요... 왜 이런건지 잘 모르겠어요 도와주세요 ㅜㅜ

**Comment by newstars** [comment]
안녕하세요~

일단 주신 코드 상으로는 xls가 파일명 전부인거죠?

파일명이 틀렸어도 저 에러는 아닐꺼라... 코드 상으로는 문제 없어 보여요.

**Comment by Kuuaba** [comment]
데이터세트 저장이 왜 안되ㅡㄴ 걸까요 ㅠㅠ
