### ISSUE TITLE
csv와 xlsx 차이가 궁금합니다.

### ISSUE THREAD

**Issue by tchumee** [newstars/HelloR#47]
안녕하세요 이 책으로 처음 r 공부를 하고 있는 독자입니다. 
다름이 아니라 챕터 4에서 모르는 부분이 생겨 질문 드립니다.
치킨집과 미세먼지 프로젝트에서는 엑셀파일을 xlsx 파일로 저장했는데, 지하철주변 아파트 가격 프로젝트에서는 csv 파일로 저장하는 이유가 무엇인지 궁금합니다. xlsx파일로 저장하면 안 되는 이유가 있는지요?
덧붙여 치킨집 프로젝트에서는 엑셀의 필터 기능을 사용한 후 결과를 복사하여 새로운 엑셀 파일로 저장했는데, 지하철주변 프로젝트에서는 똑같이 필터 기능을 사용했는데도 새로운 엑셀파일에 옮기지 않고 그대로 다른이름으로 저장을 하는 이유도 알고 싶습니다.
좋은 책 감사합니다!

**Comment by newstars** [comment]
안녕하세요.

csv와 xlsx 는 파일 형태의 차이입니다.

csv는 text 기반이고, xlsx는 ms에서 만든 포맷이구요.

실습을 위해 다양한 파일로 진행하는 예시를 찾은 것입니다.

공공데이터에서 제공하는 파일 확장자를 사용해서 실습을 한 것입니다.

필터링이나 파일을 별도로 저장하거나 메모리로 처리하는 것 
역시 다양한 사용 방법중에 하나 일 뿐입니다.

감사합니다.
