### ISSUE TITLE
install_github('dkahle/ggmap') 오류 문의드립니다.

### ISSUE THREAD

**Issue by tchumee** [newstars/HelloR#48]
질문 답변 잘 받았습니다 감사합니다.
이번에는 구글지도 관련하여 오류가 발생하여 질문드립니다.
이런식으로 나오는데 어떻게 해야 할까요?

> install_github('dkahle/ggmap')
Downloading GitHub repo dkahle/ggmap@HEAD
/usr/bin/tar: "C\:\\Users\\\354\235\264\354\210\230\353\257\274\\AppData\\Local\\Temp\\RtmpW83may\\file2bf42eff62c3.tar.gz": Cannot open: No such file or directory
/usr/bin/tar: Error is not recoverable: exiting now
External tar failed with `--force-local`, trying without
/usr/bin/tar: "C\:\\Users\\\354\235\264\354\210\230\353\257\274\\AppData\\Local\\Temp\\RtmpW83may\\file2bf42eff62c3.tar.gz": Cannot open: No such file or directory
/usr/bin/tar: Error is not recoverable: exiting now
External tar failed with `--force-local`, trying without
에러: Failed to install 'ggmap' from GitHub:
  Does not appear to be an R package (no DESCRIPTION)
추가정보: 경고메시지(들): 
1: utils::untar(tarfile, ...)에서:
  ‘tar.exe -xf "C:\Users\이수민\AppData\Local\Temp\RtmpW83may\file2bf42eff62c3.tar.gz" -C "C:/Users/이수민/AppData/Local/Temp/RtmpW83may/remotes2bf42e463b9c"’ returned error code 2
2: system(cmd, intern = TRUE)에서:
  명령 'tar.exe -tf "C:\Users\이수민\AppData\Local\Temp\RtmpW83may\file2bf42eff62c3.tar.gz"'의 실행으로 상태 2가 되었습니다
>

**Comment by newstars** [comment]
"C:\Users\\354\235\264\354\210\230\353\257\274\AppData\Local\Temp\RtmpW83may\file2bf42eff62c3.tar.gz": Cannot open: No such file or directory

에러 문구에서 보시면 알수 있듯이 한글 문제 입니다.

C:\Users\이수민\ 한글로 생성하셔서 발생하는 문제입니다..ㅠㅠ

**Comment by newstars** [comment]
보통 이럴 경우 방법이...

**1. 윈도우 계정을 영문으로 새로 만든다.**
> 수정할 경우 경로까지 수정이 안되서 새로 만들어야 합니다.

**2. 패키지 설치 경로 변경**
> .libPaths("경로") 로 설정 가능합니다. 제대로 설정됐는지는 .libPaths() 로 확인 가능합니다.
