### ISSUE TITLE
오류

### ISSUE THREAD

**Issue by MINAKOO** [newstars/HelloR#5]
KoNLP패키지 로드 후 시스템 사전 설정하는 과정에서 오류가 발생합니다.
> library(KoNLP)
Building dictionary structures.

> useSystemDic()
Backup was just finished!
Downloading package from url: https://github.com/haven-jeon/NIADic/releases/download/0.0.1/NIADic_0.0.1.tar.gz
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot open URL 'https://github.com/haven-jeon/NIADic/releases/download/0.0.1/NIADic_0.0.1.tar.gz'
> useSejongDic()
Backup was just finished!
Downloading package from url: https://github.com/haven-jeon/NIADic/releases/download/0.0.1/NIADic_0.0.1.tar.gz
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot open URL 'https://github.com/haven-jeon/NIADic/releases/download/0.0.1/NIADic_0.0.1.tar.gz'
> useNIADic()
Backup was just finished!
Downloading package from url: https://github.com/haven-jeon/NIADic/releases/download/0.0.1/NIADic_0.0.1.tar.gz
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot open URL 'https://github.com/haven-jeon/NIADic/releases/download/0.0.1/NIADic_0.0.1.tar.gz'

어떻게 하면 해결될까요?

**Comment by newstars** [comment]
혹시 인터넷이 안됐던것일까요?

URL을 입력해도 현재로서는 잘 연결되는 상태라서, 계속 그 상태이시면 수동 설치하셔야 할듯 합니다.

정상적으로 설치하실 경우 다음과 같이 경로가 나옵니다.
> system.file(package = 'NIADic')
[1] "/Library/Frameworks/R.framework/Versions/3.5/Resources/library/NIADic"

만약 그렇지 않다면, 
https://github.com/haven-jeon/NIADic/releases/download/0.0.1/NIADic_0.0.1.tar.gz

파일을 받으시고, 수동 설치를 진행합니다.
 install.packages('/Users/newstars/Download/NIADic_0.0.1.tar.gz', repos = NULL, type="source")

혹은  Rstudio 에서 Tools > Install Packages 로 설치하시면 됩니다.

그리고 다시 설치 확인해보시면 됩니다.
