### ISSUE TITLE
4장 p81

### ISSUE THREAD

**Issue by kiyeon0769** [newstars/HelloR#50]
install.packages('readxl')

library(readxl)
위의 코드를 입력하고 실행하면 콘솔창에 아래와 같이 나오는데 어떻게 해결해야 하나요?

> install.packages("readxl") Warning in install.packages :   'lib = "C:/Program Files/R/R-4.1.3/library"' is not writable Warning in install.packages :   cannot create dir 'C:\Users\82108\OneDrive\??', reason 'Invalid argument' Error in install.packages : unable to create ‘C:/Users/82108/OneDrive/??/R/win-library/4.1’ > library(readxl) Warning messages: 1: In normalizePath(path.expand(path), winslash, mustWork) :   path[1]="C:/Users/82108/OneDrive/??": 파일 이름, 디렉터리 이름 또는 볼륨 레이블 구문이 잘못되었습니다 2: In normalizePath(path.expand(path), winslash, mustWork) :   path[1]="C:/Users/82108/OneDrive/??": 파일 이름, 디렉터리 이름 또는 볼륨 레이블 구문이 잘못되었습니다
--

**Comment by newstars** [comment]
안녕하세요.

C:/Users/82108/OneDrive/??/R/win-library/4.1

경로가 저 ?? 부분이 한글인가요?

**Comment by kiyeon0769** [comment]
네 영어로 바꿨더니 해결됐어요!

**Comment by newstars** [comment]
네네 한글을 지원하지 않아서 그렇습니다.
