### ISSUE TITLE
ggmap

### ISSUE THREAD

**Issue by dlwlsgml5** [newstars/HelloR#6]
안녕하세요 선생님
ggmap 패키지를 사용하고 싶은데 자꾸 안 돼서 질문 남겨요

library(ggmap)
이렇게 실행을 시키면 자꾸 밑에처럼 떠요... 어떻게 해야 되나요?

> library(ggmap)
필요한 패키지를 로딩중입니다: ggplot2

Error: package or namespace load failed for ‘ggmap’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):

 ‘bitops’이라고 불리는 패키지가 없습니다

**Comment by newstars** [comment]
안녕하세요. 패키지 의존성 문제로 판단됩니다.

우선 ggmap 을 삭제하시고 다시 설치하세요.

remove.packages("ggmap"))
install.packages('bitops', dependencies = TRUE)

이걸 먼저 설치하시고, 이후에 ggmap을 설치하시면 됩니다.

지금 최신 버전은 3.0.0.900 입니다.
감사합니다.
