### ISSUE TITLE
treemap 한글 깨짐

### ISSUE THREAD

**Issue by llewyn-jh** [newstars/HelloR#7]
안녕하세요. 저는 mac 사용자인데요, treemap 을 사용할 때 plot 창에 한글이 'ㅁ' 로 표기됩니다.
이 현상을 어떻게 해결해야하나요?

**Comment by newstars** [comment]
안녕하세요. 맥 폰트 문제입니다.
treemap(addr_count, index=".", vSize="Freq", title="서대문구 동별 치킨집 분표", fontfamily.labels="AppleGothic")
맥용 폰트를 설정해시면 됩니다.﻿ 
감사합니다.
